### ISSUE TITLE
添加此扩展组件后，小程序开发工具IDE里上传版本失败

### ISSUE THREAD

**Issue by DFSeventeen** [ant-design/ant-design-mini#559]
## 基础库版本

- [ ] 1.x
- [ ] 2.x

## 手机系统

- [ ] iOS
- [ ] Android
- [ ] HarmonyOS

## 复现步骤 

1. 
2. 

## 复现 demo

fork fail(1):
/var/fc/lang/nodejs14_alinode/bin/node

Module build failed (from /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_@ali_antcube-build@0.73.17@@ali/antcube-build/lib/build/loader/engine/shared/axml/entry.js):
Error: Can't resolve 'antd-mini/es/Picker/index' in '/tmp/data/build/pages/selectRegion'
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/Resolver.js:209:21
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_tapable@1.1.3@tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /tmp/miniBuilder/install-path/antcube_miniBuilderSub_antcube_0.73.17/node_modules/_enhanced-resolve@4.5.0@enhanced-resolve/lib/forEachBail.js:30:14
Module build fai

**Comment by jc9702507** [comment]
本地开发是对的不？看起来报错是 `Can't resolve 'antd-mini/es/Picker/index'`，是否 usingComponent 使用错了，对比 https://ant-design-mini.antgroup.com/components/picker
